icons = [
    "send",
    "inbox",
    "update",
    "search-folder",
    "edit-find",
    "address-book",
    "edit",
    "user-trash",
    "warning-outline",
    "minus-circle-outline",
    "info-outline",
    "success-small",
    "copy",
    "menu",
]
