[package]
name = "aporture_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
# NOTE: Shared dependencies
serde = { workspace = true }
serde_bencode = { workspace = true }
serde_with = { workspace = true }
serde_repr = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
