[package]
name = "aporture_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
blake3 = { version = "1.5.1", optional = true }
aes-gcm-siv = { version = "0.11.1", optional = true }
spake2 = { version = "0.4.0", optional = true }
directories = { version = "5.0.1", optional = true }
local-ip-address = { version = "0.6.1", optional = true }
igd = { version = "0.14.3", package = "igd-next", optional = true, features = [
    "aio_tokio",
] }
thiserror = { version = "1.0.58", optional = true }

# NOTE: Protocol dependencies
serde = { version = "1.0.197", features = ["derive"] }
serde_bencode = "0.2.4"
serde_with = "3.7.0"
serde_repr = "0.1.18"
generic-array = "1.0.0"
rand = "0.8.5"

# NOTE: Shared dependencies
tokio = { workspace = true }
log = { workspace = true }

[features]
default = ["full"]
full = [
    "dep:blake3",
    "dep:aes-gcm-siv",
    "dep:spake2",
    "dep:directories",
    "dep:local-ip-address",
    "dep:igd",
    "dep:thiserror",
]
