[package]
name = "aporture_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dev-dependencies]
paste = "1.0.15"

[dependencies]
blake3 = { version = "1.5.4", optional = true }
argon2 = { version = "0.5.3", optional = true, default-features = false, features = [
    "alloc",
] }
aes-gcm-siv = { version = "0.11.1", optional = true }
spake2 = { version = "0.4.0", optional = true }
directories = { version = "5.0.1", optional = true }
local-ip-address = { version = "0.6.3", optional = true }
igd = { version = "0.15.0", package = "igd-next", optional = true, features = [
    "aio_tokio",
] }
chrono = { version = "0.4.38", optional = true, features = ["serde"] }
bytes = "1.7.2"

# NOTE: Protocol dependencies
serde = { version = "1.0.210", features = ["derive"] }
serde_bencode = "0.2.4"
serde_with = "3.9.0"
serde_repr = "0.1.19"
generic-array = "1.1.0"
rand = "0.8.5"

# NOTE: Shared dependencies
tokio = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
tar = "0.4.42"
flate2 = "1.0.34"

[features]
default = ["full"]
full = [
    "blake3",
    "argon2",
    "aes-gcm-siv",
    "spake2",
    "directories",
    "local-ip-address",
    "igd",
    "chrono",
]
