[package]
name = "aporture_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_bencode = "0.2.4"
serde_with = "3.4.0"
serde_repr = "0.1.17"
spake2 = "0.4.0"
sha2 = "0.10.8"
blake3 = "1.5.0"
aes-gcm-siv = "0.11.1"
