name: rust
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build: 
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: "Build the"
        run: cargo build 
      - name: "Runs all tests"
        run: cargo test --all-features
      - name: "Runs clippy"
        run: cargo clippy -- --deny warnings
      - name: "Runs formatter"
        run: cargo fmt --all -- --check
  