name: rust
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build: 
    name: "Builds, tests and lints the project"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up GTK
        uses: actions/setup-gtk@v2
        with:
          channels: stable
          version: latest

      - name: "Runs formatter"
        run: cargo fmt --all -- --check

      - name: "Runs clippy"
        run: cargo clippy -- --deny warnings

      - name: "Runs all tests"
        run: cargo test --all-features

      - name: "Build"
        run: cargo build 
  