name: rust
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build: 
    name: "Builds, tests and lints the project"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-dev \
            libadwaita-1-dev \
            libglib2.0-dev \
            libgdk-pixbuf2.0-dev \
            libpango-1.0-dev \
            libatk1.0-dev \
            libcairo2-dev \
            xorg-dev \
            libdbus-1-dev \
            libxml2-dev \
            meson \
            ninja-build \
            wayland-protocols

      - name: "Runs formatter"
        run: cargo fmt --all -- --check

      - name: "Runs clippy"
        run: cargo clippy -- --deny warnings

      - name: "Runs all tests"
        run: cargo test --all-features

      - name: "Build"
        run: cargo build 
  