name: rust
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: "Builds, tests and lints the project"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msambartolomeo/fedora_gtk:latest
      credentials:
        username: msambartolomeo
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: "Runs formatter"
        run: cargo fmt --all -- --check

      - name: "Build"
        run: cargo build

      - name: "Runs clippy"
        run: cargo clippy -- --deny warnings

      - name: "Runs all tests"
        run: cargo test --all-features
